export const PERSONAS = [
  { id: "ibrahima", name: "Ibrahima Diop", age: 36, title: "The Digital Progressive", color: "#2E7D32", colorLight: "#E8F5E9", initial: "I" },
  { id: "fatou", name: "Fatou Sarr", age: 48, title: "The Aspiring Community Leader", color: "#00796B", colorLight: "#E0F2F1", initial: "F" },
  { id: "ousmane", name: "Ousmane Ba", age: 64, title: "The Modest Offline Farmer", color: "#5D4037", colorLight: "#EFEBE9", initial: "O" },
  { id: "aissatou", name: "Aissatou Diallo", age: 38, title: "The Connected Communicator", color: "#6A1B9A", colorLight: "#F3E5F5", initial: "A" },
  { id: "moussa", name: "Moussa Sow", age: 52, title: "The Traditional Grower", color: "#BF360C", colorLight: "#FBE9E7", initial: "M" },
];

export const P_MAP = Object.fromEntries(PERSONAS.map(p => [p.id, p]));

export const TEAMS = ["Sales", "Data", "Engineering", "Product", "Leadership", "IT", "Development", "Supply Chains & Logistics", "Accounting & Finance", "Government Relations", "Call Center"];

export const TIMER_SECS = { 1: 30, 2: 40, 3: 50 };

export const GAME1_QS = [
  { d:1, type:"single", q:"I'm the only persona who can read and write in French. I use Google to search for farming tips. Who am I?", correct:["ibrahima"], explanation:"Ibrahima is the only French-literate persona (22.4%) and uses Google (36.6%).", hint:"Literacy is the key differentiator.", about:["ibrahima"] },
  { d:1, type:"single", q:"I'm the oldest persona at 64 years old. I use a horse cart for transport. Who am I?", correct:["ousmane"], explanation:"Ousmane is 64, the oldest persona, and uses a horse cart (65.7%).", hint:"Check the ages...", about:["ousmane"] },
  { d:1, type:"single", q:"I'm active in my women's group and I grow hibiscus as my primary crop. Who am I?", correct:["fatou"], explanation:"Fatou is the only persona in a women's group (22.2%) and grows hibiscus (45.8%).", hint:"Which persona is female and community-focused?", about:["fatou"] },
  { d:1, type:"single", q:"My advice to new farmers is 'the land doesn't lie.' I grow cowpea as one of my crops. Who am I?", correct:["moussa"], explanation:"Moussa is the only persona who grows cowpea (29.7%) and his quote is about the land not lying.", hint:"Only one persona grows cowpea...", about:["moussa"] },
  { d:1, type:"single", q:"I use social media to stay informed and connected. I follow news on Facebook. Who am I?", correct:["aissatou"], explanation:"Aissatou uses social media to communicate (51.2%) and stay informed (46.5%), follows news on Facebook (45.1%).", hint:"Who is the social media persona?", about:["aissatou"] },
  { d:2, type:"single", q:"I discovered myAgro at a village meeting, not through a VE or friend. I've attended at least one training and my goal is to diversify my crops. Who am I?", correct:["fatou"], explanation:"Fatou found myAgro at a village meeting (26.1%), has attended training (28%), and wants to diversify crops (29%).", hint:"Think discovery channel + goal combination...", about:["fatou"] },
  { d:2, type:"single", q:"I participate in WhatsApp groups, use social media for information, and teach new techniques to others. I have a car for transport services. Who am I?", correct:["ibrahima"], explanation:"Ibrahima uses WhatsApp groups (73.9%), social for info (51.2%), teaches others (19.6%), and has a car/moto (48.1%).", hint:"Full digital engagement + teaching role...", about:["ibrahima"] },
  { d:2, type:"single", q:"My primary strategy is simply to work harder. I have 15+ years of experience and I use Wave for deposits. I'm not in any farmer groups. Who am I?", correct:["moussa"], explanation:"Moussa's strategy is hard work (32%), has 15+ years (42.8%), uses Wave (73.6%), and is not a group member (48.6%).", hint:"Traditional values, simple approach...", about:["moussa"] },
  { d:2, type:"single", q:"I supplement my farming with small trade year-round. I found myAgro through my VE and my goal is to save and invest for the future. Who am I?", correct:["ousmane"], explanation:"Ousmane does small trade (29.7%) year-round (52%), found via VE (62.7%), goal is to save/invest (31%).", hint:"Savings-focused + small trade combination...", about:["ousmane"] },
  { d:2, type:"single", q:"I grow groundnut, millet, and maize. My strategy is to buy quality inputs. I keep livestock for year-round income. Who am I?", correct:["aissatou"], explanation:"Aissatou grows groundnut/millet/maize, strategy is quality inputs (30%), keeps livestock (36.78%) year-round.", hint:"Maize is the distinguishing tertiary crop...", about:["aissatou"] },
  { d:3, type:"single", q:"I rate my performance as 'Very Good,' measure success by goals achieved, and I'm proudest of learning. My secondary crop is watermelon. Who am I?", correct:["ibrahima"], explanation:"Ibrahima rates 'Very Good' (14.4%), measures by goals (20.9%), proud of learning (12%), grows watermelon (7.3%).", hint:"Self-assessment + secondary crop narrows it down...", about:["ibrahima"] },
  { d:3, type:"single", q:"I rate myself 'Average,' my biggest challenge is labor shortage, and my solution is to adjust inputs. I measure success by how well I support my family. Who am I?", correct:["fatou"], explanation:"Fatou rates 'Average' (34.8%), faces labor (16%), adjusts inputs (14%), measures by family support (24.2%).", hint:"Family-centered success metric is the key...", about:["fatou"] },
  { d:3, type:"single", q:"My main challenge is animals damaging crops. My solution is careful spending. I have no formal role, no groups, use Wave but no trainings. Who am I?", correct:["ousmane"], explanation:"Ousmane faces animals (17%), spends carefully (56%), no role (63.2%), no groups (48.6%), Wave, no training (63%).", hint:"Stack all the 'none' attributes together...", about:["ousmane"] },
  { d:3, type:"single", q:"I contact my VE once a month. I use smartphone for voice but am active on WhatsApp and follow Facebook news. My proudest achievement is good harvests. Who am I?", correct:["aissatou"], explanation:"Aissatou contacts VE 1x/month (41.8%), smartphone for voice, WhatsApp (73.9%), Facebook news (45.1%), proud of harvests.", hint:"VE contact frequency + social media combo...", about:["aissatou"] },
  { d:3, type:"single", q:"I have 15+ years on 1-5 hectares. I grow groundnut, millet, and cowpea. I prefer phone calls and participate in WhatsApp groups. Who am I?", correct:["moussa"], explanation:"Moussa has 15+ years (42.8%), 1-5 ha (54.9%), cowpea (29.7%), prefers calls (78.6%), WhatsApp groups (38.1%).", hint:"Cowpea is the unique crop identifier...", about:["moussa"] },
  { d:2, type:"single", q:"I process products and take on casual labor to supplement irregular income. I check TikTok on other people's phones. Who am I?", correct:["fatou"], explanation:"Fatou does processing (18.6%), has irregular income, checks TikTok on others' phones (29.2%).", hint:"Who borrows others' phones for TikTok?", about:["fatou"] },
  { d:2, type:"single", q:"I'm a savings group member who contacts myAgro weekly and prefers WhatsApp. I have less than 0.5 hectares. Who am I?", correct:["ibrahima"], explanation:"Ibrahima is in a savings group (8.8%), contacts weekly (10%), prefers WhatsApp (22.1%), farms <0.5 ha (17.1%).", hint:"Small land + frequent digital contact...", about:["ibrahima"] },
  { d:3, type:"single", q:"I sell most of my harvest. My secondary crop is hibiscus. I earn from small trade year-round and found myAgro through my VE. I carefully manage every expense. Who am I?", correct:["ousmane"], explanation:"Ousmane sells most (35.8%), hibiscus secondary (45.8%), trades year-round, found via VE (62.7%), spends carefully (56%).", hint:"Selling most + secondary hibiscus...", about:["ousmane"] },
  { d:3, type:"single", q:"My main issue is input costs at 43%. I need fertilizers and seeds (44%). I advise 'work hard' (41%) and 'use good inputs' (15%). I measure success by income. Who am I?", correct:["aissatou"], explanation:"Aissatou faces input costs (43%), needs fertilizers/seeds (44%), advises hard work (41%) and good inputs (15%), measures by income (44.3%).", hint:"The data sheet percentages are very specific...", about:["aissatou"] },
  { d:1, type:"single", q:"I earn extra income from livestock year-round. My strategy is hard work. I believe 'the land doesn't lie.' Who am I?", correct:["moussa"], explanation:"Moussa earns from livestock (36.78%) year-round (52%), strategy is hard work (32%).", hint:"Traditional, hard-working, livestock income...", about:["moussa"] },
];

export const GAME2_QS = [
  { d:1, type:"single", q:"Which persona has NO mobile money registration and has NEVER used mobile money?", correct:["fatou"], explanation:"Fatou is the only persona not registered (22.4%) and never used mobile money (21.6%).", hint:"Who is most disconnected from digital finance?", about:["fatou"] },
  { d:1, type:"single", q:"Which persona found myAgro through a friend — not a VE or village meeting?", correct:["ibrahima"], explanation:"Ibrahima found myAgro through a friend (10.7%).", hint:"Digitally connected, found it socially...", about:["ibrahima"] },
  { d:1, type:"single", q:"Which persona's main farming challenge is animals damaging their crops?", correct:["ousmane"], explanation:"Ousmane faces animals (17%). Others face pests, labor, or input costs.", hint:"Rural, larger land...", about:["ousmane"] },
  { d:1, type:"multi", q:"Which personas use Wave for mobile money? Select all that apply.", correct:["ibrahima","ousmane","aissatou","moussa"], explanation:"All use Wave (73.6%) except Fatou who has no mobile money.", hint:"Almost everyone except one...", about:["fatou","ibrahima","ousmane","aissatou","moussa"] },
  { d:1, type:"single", q:"Which persona's primary goal is to 'diversify crops and activities'?", correct:["fatou"], explanation:"Fatou wants to diversify (29%).", hint:"She grows hibiscus and okra and wants more variety...", about:["fatou"] },
  { d:2, type:"multi", q:"Which personas have NEVER attended a myAgro training? Select all.", correct:["ousmane","aissatou","moussa"], explanation:"All three show 63% 'None' for trainings. Ibrahima attended multiple and Fatou at least 1.", hint:"More than two share this...", about:["ousmane","aissatou","moussa"] },
  { d:2, type:"multi", q:"Which personas earn year-round income (not just seasonal)? Select all.", correct:["ousmane","aissatou","moussa"], explanation:"Ousmane (trade), Aissatou (livestock), Moussa (livestock) earn year-round (52%).", hint:"Think income beyond crops...", about:["ousmane","aissatou","moussa"] },
  { d:2, type:"single", q:"Which persona contacts their VE weekly — more frequently than all others?", correct:["ibrahima"], explanation:"Ibrahima contacts weekly (10%). Others contact 2-3x/month or 1x/month.", hint:"The most engaged persona...", about:["ibrahima"] },
  { d:2, type:"multi", q:"Which personas prefer phone calls as their main communication? Select all.", correct:["fatou","ousmane","aissatou","moussa"], explanation:"All except Ibrahima prefer calls (78.6%). Ibrahima prefers WhatsApp (22.1%).", hint:"Only one prefers a different channel...", about:["fatou","ousmane","aissatou","moussa","ibrahima"] },
  { d:2, type:"single", q:"Which persona rates their performance as 'Very Good'?", correct:["ibrahima"], explanation:"Ibrahima rates 'Very Good' (14.4%). Others rate 'Average' or 'Good'.", hint:"The most confident persona...", about:["ibrahima"] },
  { d:3, type:"multi", q:"Which personas use a smartphone (not basic phone)? Select all.", correct:["ibrahima","aissatou","moussa"], explanation:"Ibrahima, Aissatou, Moussa use smartphones (58%). Fatou and Ousmane use basic phones (42%).", hint:"Device type splits personas into two groups...", about:["ibrahima","aissatou","moussa","fatou","ousmane"] },
  { d:3, type:"single", q:"Which persona's secondary crop is watermelon?", correct:["ibrahima"], explanation:"Ibrahima grows watermelon as secondary (7.3%).", hint:"Small plot, vegetable farmer...", about:["ibrahima"] },
  { d:3, type:"multi", q:"Which personas have 'no formal community role' (63.2%)? Select all.", correct:["ousmane","aissatou","moussa"], explanation:"Ibrahima is a teacher (19.6%) and Fatou has skills (23.2%).", hint:"Check the Community & Personal section...", about:["ousmane","aissatou","moussa"] },
  { d:3, type:"single", q:"Which persona measures success specifically by 'yield' (37.5%)?", correct:["ousmane"], explanation:"Ousmane measures by yield. Others measure by goals, family, or income.", hint:"Harvest output focused...", about:["ousmane"] },
  { d:3, type:"multi", q:"Which personas grow groundnut as primary crop? Select all.", correct:["ousmane","aissatou","moussa"], explanation:"All three grow groundnut (63.7%). Ibrahima grows vegetables, Fatou grows hibiscus.", hint:"Groundnut is the dominant crop in Senegal...", about:["ousmane","aissatou","moussa"] },
  { d:2, type:"single", q:"Which persona's main challenge is specifically labor shortage (16%)?", correct:["fatou"], explanation:"Fatou faces labor shortage (16%).", hint:"Think about who might lack helping hands...", about:["fatou"] },
  { d:3, type:"multi", q:"Which personas are NOT members of any community groups (48.6%)? Select all.", correct:["ousmane","aissatou","moussa"], explanation:"Ibrahima is in a savings group and Fatou is in a women's group.", hint:"The three who also haven't attended training...", about:["ousmane","aissatou","moussa"] },
  { d:2, type:"single", q:"Which persona uses Orange Money in addition to Wave?", correct:["ibrahima"], explanation:"Ibrahima uses both Wave (73.6%) and Orange Money (25.9%).", hint:"The most digitally advanced persona...", about:["ibrahima"] },
  { d:1, type:"single", q:"Which persona is proudest of 'supporting family and household success'?", correct:["fatou"], explanation:"Fatou measures success by family support (24.2%).", hint:"Family-focused persona...", about:["fatou"] },
  { d:3, type:"single", q:"Which persona advises new farmers to 'start small, learn as you go, and gradually expand'?", correct:["fatou"], explanation:"This is Fatou's direct quote and advice.", hint:"Cautious, growth-minded advice...", about:["fatou"] },
];

export const GAME3_QS = [
  { d:1, type:"single", q:"You're designing a payment feature that only works via app. Which persona is MOST excluded?", correct:["fatou"], explanation:"Fatou has a basic phone, voice only, no mobile money, no other tech — the most stacked barriers.", hint:"Basic phone + no mobile money = most excluded.", about:["fatou"] },
  { d:1, type:"single", q:"You want to send farming tips via WhatsApp text messages. Which persona benefits MOST?", correct:["ibrahima"], explanation:"Ibrahima is the only persona who can read, uses WhatsApp groups actively, and seeks info digitally.", hint:"Who can actually read the messages?", about:["ibrahima"] },
  { d:1, type:"multi", q:"You're building a voice-based IVR system. Which personas would this work well for? Select all.", correct:["fatou","ousmane","aissatou","moussa"], explanation:"All except Ibrahima prefer phone calls (78.6%).", hint:"Who prefers phone calls?", about:["fatou","ousmane","aissatou","moussa"] },
  { d:1, type:"single", q:"A new feature requires reading a text menu. Which persona represents the non-literate majority who would struggle?", correct:["ousmane"], explanation:"79.3% can't read/write. Ousmane represents this majority as the offline-first persona.", hint:"Think about literacy rates...", about:["ousmane","fatou","aissatou","moussa"] },
  { d:1, type:"single", q:"You need to reach farmers through Village Entrepreneurs. Which persona was NOT discovered through a VE?", correct:["ibrahima"], explanation:"Ibrahima found myAgro through a friend (10.7%).", hint:"Two personas have non-VE discovery channels...", about:["ibrahima"] },
  { d:2, type:"multi", q:"You're running a Facebook marketing campaign. Which personas might see it? Select all.", correct:["ibrahima","aissatou","moussa"], explanation:"Ibrahima uses Facebook for fun (27.2%), Aissatou follows news (45.1%), Moussa follows news (45.1%).", hint:"Check who has active Facebook usage...", about:["ibrahima","aissatou","moussa"] },
  { d:2, type:"single", q:"You're designing a savings goal tracker. Which persona's primary goal makes them the ideal first user?", correct:["ousmane"], explanation:"Ousmane's goal is to 'save/invest for the future' (31%).", hint:"Which persona's goal is literally about saving?", about:["ousmane"] },
  { d:2, type:"single", q:"A stakeholder wants a complex budgeting spreadsheet feature. Which persona's quote best argues against this?", correct:["moussa"], explanation:"Moussa says 'The land doesn't lie' — he values simplicity. Plus 79% can't read.", hint:"Who values keeping things simple?", about:["moussa"] },
  { d:2, type:"multi", q:"You need non-literate farmers for testing. Which personas represent this segment? Select all.", correct:["fatou","ousmane","aissatou","moussa"], explanation:"All except Ibrahima cannot read/write (79.3%).", hint:"79% can't read — that's 4 out of 5 personas.", about:["fatou","ousmane","aissatou","moussa"] },
  { d:2, type:"single", q:"You want to pilot WhatsApp voice messages for farmer updates. Which persona's discovery channel suggests they'd respond well?", correct:["fatou"], explanation:"Fatou found myAgro at a village meeting (word-of-mouth), prefers calls, has attended training — open to engagement.", hint:"Who is reachable but needs voice format?", about:["fatou"] },
  { d:3, type:"single", q:"You're allocating budget between app development and VE training. Which persona represents the untapped potential of VE training?", correct:["ousmane"], explanation:"Ousmane found myAgro through VE, contacts 2-3x/month, but never attended training.", hint:"Strongest VE relationship + zero training?", about:["ousmane"] },
  { d:3, type:"single", q:"A PM wants a community comparison feature. Which persona's data MOST supports keeping it out?", correct:["ousmane"], explanation:"Ousmane has no groups (48.6%), no role (63.2%), focuses on individual savings.", hint:"Who is most individually focused?", about:["ousmane"] },
  { d:3, type:"multi", q:"You're onboarding farmers to pay via mobile money. Which already use Wave? Select all.", correct:["ousmane","aissatou","moussa"], explanation:"All three use Wave for deposits/withdrawals but may not use it for myAgro payments.", hint:"Who uses Wave already?", about:["ousmane","aissatou","moussa"] },
  { d:3, type:"single", q:"You need different onboarding for literate vs non-literate users. Which persona represents the ~20% literate group?", correct:["ibrahima"], explanation:"Ibrahima represents the ~20% literate segment.", hint:"Think about the 79/21 literacy split...", about:["ibrahima"] },
  { d:3, type:"single", q:"SMS text vs voice call reminders for payment deadlines — which persona best shows why voice wins?", correct:["moussa"], explanation:"Moussa: smartphone owner who still uses voice primarily. Voice covers all 5 personas.", hint:"What communication method do ALL personas use?", about:["moussa","fatou","ousmane","aissatou"] },
  { d:2, type:"multi", q:"You're planning research home visits. Which personas should you visit in person? Select all.", correct:["fatou","ousmane"], explanation:"Both have basic phones and limited digital access — phone interviews miss context.", hint:"Most limited phone capabilities?", about:["fatou","ousmane"] },
  { d:3, type:"single", q:"You want to test a visual progress tracker (icons, not text). Which persona should you test FIRST?", correct:["fatou"], explanation:"Fatou is most constrained: basic phone, no mobile money, voice only, no literacy. If it works for her, it works for everyone.", hint:"Test with the most constrained user first...", about:["fatou"] },
  { d:2, type:"single", q:"You're choosing which mobile money provider to integrate first. The data says Wave is at 73.6%. Which persona represents the typical Wave user?", correct:["aissatou"], explanation:"Aissatou represents the typical Wave user — deposits and withdrawals (78.6%).", hint:"73.6% vs 25.9% — the numbers are clear.", about:["aissatou","ousmane","moussa"] },
  { d:1, type:"multi", q:"You're creating training content. Which personas have attended at least one myAgro training? Select all.", correct:["ibrahima","fatou"], explanation:"Ibrahima attended multiple (>1) and Fatou at least 1 (28%). Others never attended (63%).", hint:"Only two have training experience...", about:["ibrahima","fatou"] },
  { d:3, type:"single", q:"An investor asks 'who is your typical farmer?' Which persona BEST represents the statistical majority?", correct:["moussa"], explanation:"Moussa hits the majority on almost every dimension: 15+ years, 1-5 ha, groundnut, smartphone, voice, Wave, VE, no training, Wolof, can't read.", hint:"Who sits at the center of the bell curve?", about:["moussa"] },
];

export const GAMES = [
  { id: "whoami", name: "Who Am I?", icon: "🧑‍🌾", desc: "Identify the persona from clues about their life and habits", color: "#2E7D32", questions: GAME1_QS },
  { id: "matchfact", name: "Match the Fact", icon: "📊", desc: "Connect data points and percentages to the right persona", color: "#00796B", questions: GAME2_QS },
  { id: "scenario", name: "Design Scenario", icon: "🎨", desc: "Apply persona knowledge to real UX design decisions", color: "#6A1B9A", questions: GAME3_QS },
];
